name: PR Check

on:
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: ./

jobs:
  check:
    runs-on: ubuntu-22.04
    environment: development
    timeout-minutes: 7
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node version
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          check-latest: false
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Cache cargo assets
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: build-cargo-${{ hashFiles('**/Cargo.lock') }}
          
      - name: Install dependencies
        run: |
          npm cache verify
          npm ci --no-audit --prefer-offline
          deno install

      - name: Setup Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 120
          install-chromedriver: true

      - name: Run NX lint
        env:
          CHROME_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}
          EMBEDDING_API_URL : ${{ vars.EMBEDDING_API_URL }}
        run: |
          npx nx run-many -t lint --verbose
          
      - name: Run NX test
        env:
          CHROME_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}
          EMBEDDING_API_URL : ${{ vars.EMBEDDING_API_URL }}
          CI_FORCE_DENO_IN_HOST: true
        run: |
          npx nx run-many -t test --parallel=false --skip-nx-cache
